import mongoose, { Schema, Document } from 'mongoose';

export interface ICategory extends Document {
  name: string;
  slug: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

const CategorySchema = new Schema<ICategory>(
  {
    name: {
      type: String,
      required: [true, 'Category name is required'],
      unique: true,
      trim: true,
    },
    slug: {
      type: String,
      required: false,  // Generated by pre-save hook
      unique: true,
      lowercase: true,
      sparse: true,  // Allow null values for unique index
    },
    description: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

// Helper function to capitalize each word
function toTitleCase(str: string): string {
  return str
    .toLowerCase()
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// Create slug and capitalize name before saving
CategorySchema.pre('save', function (next) {
  // Always capitalize the name if it's being set or modified
  if (this.name && (this.isNew || this.isModified('name'))) {
    // Capitalize the name (Title Case)
    this.name = toTitleCase(this.name.trim());
    
    // Generate slug from name
    this.slug = this.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
  
  // Fallback: if slug is still not set, generate it now
  if (!this.slug && this.name) {
    this.slug = this.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
  
  next();
});

export default mongoose.models.Category || mongoose.model<ICategory>('Category', CategorySchema);

