import mongoose, { Schema, Document } from 'mongoose';

export interface ISubcategory extends Document {
  name: string;
  slug: string;
  category: mongoose.Types.ObjectId;
  imageUrl?: string;
  createdAt: Date;
  updatedAt: Date;
}

const SubcategorySchema = new Schema<ISubcategory>(
  {
    name: {
      type: String,
      required: [true, 'Subcategory name is required'],
      trim: true,
    },
    slug: {
      type: String,
      required: false,  // Generated by pre-save hook
      lowercase: true,
    },
    category: {
      type: Schema.Types.ObjectId,
      ref: 'Category',
      required: [true, 'Category is required'],
    },
    imageUrl: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

// Create compound unique index on name and category to allow same subcategory name in different categories
SubcategorySchema.index({ name: 1, category: 1 }, { unique: true });

// Helper function to capitalize each word
function toTitleCase(str: string): string {
  return str
    .toLowerCase()
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// Create slug and capitalize name before saving
SubcategorySchema.pre('save', function (next) {
  // Always capitalize the name if it's being set or modified
  if (this.name && (this.isNew || this.isModified('name'))) {
    // Capitalize the name (Title Case)
    this.name = toTitleCase(this.name.trim());
    
    // Generate slug from name
    this.slug = this.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
  
  // Fallback: if slug is still not set, generate it now
  if (!this.slug && this.name) {
    this.slug = this.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
  
  next();
});

// Clear the model if it exists to force recompilation with new schema
if (mongoose.models.Subcategory) {
  delete mongoose.models.Subcategory;
}

export default mongoose.model<ISubcategory>('Subcategory', SubcategorySchema);


